[build]

[target.x86_64-unknown-linux-gnu]
# Use frame pointers since the dispatch breaks perf call traces
rustflags = [
	"-Cforce-frame-pointers=on",
	"-Zbox-noalias=false",
	"-Zmutable-noalias=false",
	# "-Zsanitizer=address"
]
